import { Event } from "react-mui-scheduler";

const stages = [
  { label: "Main", color: "#d7930f" },
  { label: "Resistance", color: "#00b6c2" },
  { label: "UMF Radio", color: "#65baed" },
  { label: "Oasis", color: "#f4c676" },
];

const mainStageDay1: Event[] = [
  {
    id: "plastik-funk",
    label: "Plastik Funk",
    date: "2023-07-07",
    startHour: "20:00",
    endHour: "21:30",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "gryffin",
    label: "Gryffin",
    date: "2023-07-07",
    startHour: "21:40",
    endHour: "23:10",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "oliver-heldens",
    label: "Oliver Heldens",
    date: "2023-07-07",
    startHour: "23:15",
    endHour: "00:45",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "axwell",
    label: "Axwell",
    date: "2023-07-08",
    startHour: "00:50",
    endHour: "2:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "zedd",
    label: "Zedd",
    date: "2023-07-08",
    startHour: "2:10",
    endHour: "3:20",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "hardwell",
    label: "Hardwell",
    date: "2023-07-08",
    startHour: "3:30",
    endHour: "5:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
];
const mainStageDay2: Event[] = [
  {
    id: "mykris",
    label: "Mykris",
    date: "2023-07-08",
    startHour: "20:00",
    endHour: "21:30",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "nora-en-pure",
    label: "Nora En Pure",
    date: "2023-07-08",
    startHour: "21:35",
    endHour: "23:05",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "tchami",
    label: "Tchami",
    date: "2023-07-08",
    startHour: "23:10",
    endHour: "00:40",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "dj-snake",
    label: "DJ Snake",
    date: "2023-07-09",
    startHour: "00:45",
    endHour: "2:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "timmy-trumpet",
    label: "Timmy Trumpet",
    date: "2023-07-09",
    startHour: "2:10",
    endHour: "3:40",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "steve-aoki",
    label: "Steve Aoki",
    date: "2023-07-09",
    startHour: "3:45",
    endHour: "5:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
];
const mainStageDay3: Event[] = [
  {
    id: "fedde-le-grand",
    label: "Fedde Le Grand",
    date: "2023-07-09",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "morten",
    label: "Morten",
    date: "2023-07-09",
    startHour: "21:05",
    endHour: "22:35",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "w-and-w",
    label: "W&W",
    date: "2023-07-09",
    startHour: "22:40",
    endHour: "00:10",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "afrojack",
    label: "Afrojack",
    date: "2023-07-10",
    startHour: "00:15",
    endHour: "2:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "martin-garrix",
    label: "Martin Garrix",
    date: "2023-07-10",
    startHour: "2:05",
    endHour: "3:40",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "alesso",
    label: "Alesso",
    date: "2023-07-10",
    startHour: "3:45",
    endHour: "5:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
];
const resistanceStageDay1: Event[] = [
  {
    id: "millean",
    label: "Millean",
    date: "2023-07-07",
    startHour: "19:00",
    endHour: "20:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "tomo-in-der-muhlen",
    label: "Tomo In Der Muhlen",
    date: "2023-07-07",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "hi-lo",
    label: "Hi-Lo",
    date: "2023-07-07",
    startHour: "21:00",
    endHour: "23:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "enrico-sangiuliano",
    label: "Enrico Sangiuliano",
    date: "2023-07-07",
    startHour: "23:00",
    endHour: "1:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "adam-beyer",
    label: "Adam Beyer",
    date: "2023-07-08",
    startHour: "1:00",
    endHour: "3:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "charlotte-de-witte",
    label: "Charlotte De Witte",
    date: "2023-07-08",
    startHour: "3:00",
    endHour: "5:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
];
const resistanceStageDay2: Event[] = [
  {
    id: "rory-lynam",
    label: "Rory Lynam",
    date: "2023-07-08",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "maz",
    label: "Maz",
    date: "2023-07-08",
    startHour: "21:00",
    endHour: "23:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "massano",
    label: "Massano",
    date: "2023-07-08",
    startHour: "23:00",
    endHour: "1:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "mathame",
    label: "Mathame",
    date: "2023-07-09",
    startHour: "1:00",
    endHour: "3:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "boris-brejcha",
    label: "Boris Brejcha",
    date: "2023-07-09",
    startHour: "3:00",
    endHour: "5:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
];
const resistanceStageDay3: Event[] = [
  {
    id: "ginchy",
    label: "Ginchy",
    date: "2023-07-09",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "pero-fullhouse",
    label: "Pero Fullhouse",
    date: "2023-07-09",
    startHour: "21:00",
    endHour: "23:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "juliet-fox",
    label: "Juliet Fox",
    date: "2023-07-09",
    startHour: "23:00",
    endHour: "1:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "nicole-moudaber",
    label: "Nicole Moudaber",
    date: "2023-07-10",
    startHour: "1:00",
    endHour: "3:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
  {
    id: "carl-cox",
    label: "Carl Cox",
    date: "2023-07-10",
    startHour: "3:00",
    endHour: "5:00",
    groupLabel: stages[1].label,
    color: stages[1].color,
  },
];
const umfStageDay1: Event[] = [
  {
    id: "adam-de-great",
    label: "Adam De Great",
    date: "2023-07-07",
    startHour: "19:00",
    endHour: "20:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "kdh",
    label: "KDH",
    date: "2023-07-07",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "tim-hox",
    label: "Tim Hox",
    date: "2023-07-07",
    startHour: "21:00",
    endHour: "22:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "vinne",
    label: "Vinne",
    date: "2023-07-07",
    startHour: "22:00",
    endHour: "23:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "avao",
    label: "Avao",
    date: "2023-07-07",
    startHour: "23:00",
    endHour: "0:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "jeffrey-sutorius",
    label: "Jeffrey Sutorius",
    date: "2023-07-08",
    startHour: "0:00",
    endHour: "1:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "olly-james",
    label: "Olly James",
    date: "2023-07-08",
    startHour: "1:00",
    endHour: "2:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "dr-phunk",
    label: "Dr Phunk",
    date: "2023-07-08",
    startHour: "2:00",
    endHour: "3:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "teamworx",
    label: "Teamworx",
    date: "2023-07-08",
    startHour: "3:00",
    endHour: "4:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "mr.black",
    label: "Mr.Black",
    date: "2023-07-08",
    startHour: "4:00",
    endHour: "5:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
];
const umfStageDay2: Event[] = [
  {
    id: "ana-anotnova",
    label: "Ana Anotnova",
    date: "2023-07-08",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "jan-kincl",
    label: "Jan Kincl",
    date: "2023-07-08",
    startHour: "21:00",
    endHour: "22:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "tom-bug",
    label: "Tom Bug",
    date: "2023-07-08",
    startHour: "22:00",
    endHour: "23:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "peznt",
    label: "Peznt",
    date: "2023-07-08",
    startHour: "23:00",
    endHour: "0:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "arseniyeah",
    label: "Arseniyeah",
    date: "2023-07-09",
    startHour: "0:00",
    endHour: "1:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "ivna-ji",
    label: "Ivna Ji",
    date: "2023-07-09",
    startHour: "1:00",
    endHour: "2:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "vanillaz",
    label: "Vanillaz",
    date: "2023-07-09",
    startHour: "2:00",
    endHour: "3:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "dave-caffrey",
    label: "Dave Caffrey",
    date: "2023-07-09",
    startHour: "3:00",
    endHour: "4:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "tjo",
    label: "Tjo",
    date: "2023-07-09",
    startHour: "4:00",
    endHour: "5:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
];
const umfStageDay3: Event[] = [
  {
    id: "Huy Dx",
    label: "Huy Dx",
    date: "2023-07-09",
    startHour: "20:00",
    endHour: "20:45",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Lorenzo",
    label: "Lorenzo",
    date: "2023-07-09",
    startHour: "20:45",
    endHour: "21:30",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Chris Willsman",
    label: "Chris Willsman",
    date: "2023-07-09",
    startHour: "21:30",
    endHour: "22:15",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Gil Glaze",
    label: "Gil Glaze",
    date: "2023-07-09",
    startHour: "22:15",
    endHour: "23:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Yamatomaya",
    label: "Yamatomaya",
    date: "2023-07-09",
    startHour: "23:00",
    endHour: "0:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Mike & Me",
    label: "Mike & Me",
    date: "2023-07-10",
    startHour: "0:00",
    endHour: "1:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Jimmy Clash",
    label: "Jimmy Clash",
    date: "2023-07-10",
    startHour: "1:00",
    endHour: "1:45",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Pink Panda",
    label: "Pink Panda",
    date: "2023-07-10",
    startHour: "1:45",
    endHour: "2:30",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Avadox",
    label: "Avadox",
    date: "2023-07-09",
    startHour: "2:30",
    endHour: "3:15",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Akira",
    label: "Akira",
    date: "2023-07-09",
    startHour: "3:15",
    endHour: "4:15",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
  {
    id: "Yaksa",
    label: "Yaksa",
    date: "2023-07-09",
    startHour: "4:15",
    endHour: "5:00",
    groupLabel: stages[2].label,
    color: stages[2].color,
  },
];
const oasisStageDay1: Event[] = [
  {
    id: "norberto-loco",
    label: "Norberto Loco",
    date: "2023-07-07",
    startHour: "19:00",
    endHour: "20:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "chepone",
    label: "Chepone",
    date: "2023-07-07",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "katsy-lee",
    label: "Katsy Lee",
    date: "2023-07-07",
    startHour: "21:00",
    endHour: "22:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "ketafere",
    label: "Ketafere",
    date: "2023-07-07",
    startHour: "22:00",
    endHour: "23:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "moon-shot",
    label: "Moon Shot",
    date: "2023-07-07",
    startHour: "23:00",
    endHour: "0:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "wekingz",
    label: "Wekingz",
    date: "2023-07-08",
    startHour: "0:00",
    endHour: "1:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
];
const oasisStageDay2: Event[] = [
  {
    id: "ryu-and-dante",
    label: "Ryu & Dante",
    date: "2023-07-08",
    startHour: "20:00",
    endHour: "21:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "robi-roka",
    label: "Robi Roka",
    date: "2023-07-08",
    startHour: "21:00",
    endHour: "22:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "dj-viktoria",
    label: "Dj Viktoria",
    date: "2023-07-08",
    startHour: "22:00",
    endHour: "23:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "sound-of-yaz",
    label: "Sound Of Yaz",
    date: "2023-07-08",
    startHour: "23:00",
    endHour: "0:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "markhese",
    label: "Markhese",
    date: "2023-07-09",
    startHour: "0:00",
    endHour: "1:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
];
const oasisStageDay3: Event[] = [
  {
    id: "tom-william",
    label: "Tom William",
    date: "2023-07-09",
    startHour: "20:00",
    endHour: "21:30",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "luca-santiago",
    label: "Luca Santiago",
    date: "2023-07-09",
    startHour: "21:30",
    endHour: "23:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "d3fai",
    label: "D3fai",
    date: "2023-07-09",
    startHour: "23:00",
    endHour: "0:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
  {
    id: "alex-pizzuti",
    label: "Alex Pizzuti",
    date: "2023-07-10",
    startHour: "0:00",
    endHour: "1:00",
    groupLabel: stages[3].label,
    color: stages[3].color,
  },
];

const events: Event[] = [
  ...mainStageDay1,
  ...mainStageDay2,
  ...mainStageDay3,
  ...resistanceStageDay1,
  ...resistanceStageDay2,
  ...resistanceStageDay3,
  ...umfStageDay1,
  ...umfStageDay2,
  ...umfStageDay3,
  ...oasisStageDay1,
  ...oasisStageDay2,
  ...oasisStageDay3,
];

export default events;
