import { Event } from "react-mui-scheduler";

const stages = [
  { label: "Main", color: "#d7930f" },
  { label: "Galaxy", color: "#00b6c2" },
  { label: "Alchemy", color: "#65baed" },
  { label: "Daydreaming", color: "#f4c676" },
  { label: "Fortune", color: "#fca7ad" },
  { label: "Time", color: "#ff9efd" },
];

const mainStageDay1: Event[] = [
  {
    id: "partydul-kiss-fm",
    label: "Partydul Kiss FM",
    date: "2022-08-04",
    startHour: "17:45",
    endHour: "18:45",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "david-ciente-x-irina-rimes-x-surorile-osoianu",
    label: "David Ciente x Irina Rimes x Surorile Osoianu",
    date: "2022-08-04",
    startHour: "19:00",
    endHour: "19:40",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "inna",
    label: "Inna",
    date: "2022-08-04",
    startHour: "19:55",
    endHour: "20:55",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "claptone",
    label: "Claptone",
    date: "2022-08-04",
    startHour: "21:15",
    endHour: "22:20",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "vini-vici",
    label: "Vini Vici",
    date: "2022-08-04",
    startHour: "22:25",
    endHour: "23:55",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "above-beyond",
    label: "Above & Beyond",
    date: "2022-08-05",
    startHour: "00:15",
    endHour: "01:30",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "morten",
    label: "Morten",
    date: "2022-08-05",
    startHour: "01:45",
    endHour: "03:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "steve-aoki",
    label: "Steve Aoki",
    date: "2022-08-05",
    startHour: "03:10",
    endHour: "04:50",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "manuel-riva",
    label: "Manuel Riva",
    date: "2022-08-05",
    startHour: "04:50",
    endHour: "06:30",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
];
const mainStageDay2: Event[] = [
  {
    id: "chico-rose",
    label: "Chico Rose",
    date: "2022-08-05",
    startHour: "17:00",
    endHour: "18:10",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "dirty-nano",
    label: "Dirty Nano",
    date: "2022-08-05",
    startHour: "18:20",
    endHour: "19:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "gryffin",
    label: "Gryffin",
    date: "2022-08-05",
    startHour: "19:30",
    endHour: "20:40",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "damian-and-brothers",
    label: "Damian & Brothers",
    date: "2022-08-05",
    startHour: "20:50",
    endHour: "21:35",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "g-easy",
    label: "G-Easy",
    date: "2022-08-05",
    startHour: "21:55",
    endHour: "22:55",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "paul-kalkbrenner-live",
    label: "Paul Kalkbrenner Live",
    date: "2022-08-05",
    startHour: "23:15",
    endHour: "00:45",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "don-diablo",
    label: "Don Diablo",
    date: "2022-08-06",
    startHour: "01:30",
    endHour: "02:40",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "dimitri-vegas-and-like-mike",
    label: "Dimitri Vegas & Like Mike",
    date: "2022-08-06",
    startHour: "02:55",
    endHour: "04:10",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
  {
    id: "bassjackers",
    label: "Bassjackers",
    date: "2022-08-06",
    startHour: "04:15",
    endHour: "05:00",
    groupLabel: stages[0].label,
    color: stages[0].color,
  },
];
const mainStageDay3: Event[] = [];
const mainStageDay4: Event[] = [];

const events: Event[] = [
  ...mainStageDay1,
  ...mainStageDay2,
  ...mainStageDay3,
  ...mainStageDay4,
  // {
  //   id: "",
  //   label: "",
  //   date: "",
  //   startHour: "",
  //   endHour: "",
  //   groupLabel: stages[0].label,
  //   color: stages[0].color,
  // },
];

export default events;
